### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by nickdesaulniers** [cryptocoinjs/ecdsa#21]
Hi there, this lib looks pretty useful. Is there any documentation as to it's API available?

**Comment by jprichardson** [comment]
Thanks. There was a start here: http://cryptocoinjs.com/modules/crypto/ecdsa/ but it's dated now since `ecdsa` tracks `bitcoinjs-lib` which lacks documentation on ecdsa usage. 

If you're looking for a solid Elliptic Curve crypto library, I would strongly suggest https://github.com/indutny/elliptic. It's ultimately my intent to deprecate `ecdsa` in favor of `elliptic`.

Feel free to ask any other questions if you have them :)

**Comment by nickdesaulniers** [comment]
thank you for the info, much appreciated :fireworks: :chart_with_upwards_trend:

**Comment by jprichardson** [comment]
Deprecated https://github.com/cryptocoinjs/ecdsa/commit/f464ac3885e9523aaf1886921d9c0a81b804e53b
